# Generated by Django 4.0.4 on 2022-07-08 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('somo_backend', '0002_subject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='somo_backend.subject'),
        ),
    ]
