# Generated by Django 4.0.4 on 2022-07-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somo_backend', '0014_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='category',
            field=models.CharField(choices=[('trainer', 'trainer'), ('student', 'student')], max_length=7),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(max_length=30),
        ),
    ]
