# Generated by Django 4.0.4 on 2022-07-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somo_backend', '0020_alter_customuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
