# Generated by Django 4.0.4 on 2022-07-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somo_backend', '0023_remove_customuser_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='user',
            new_name='trainer',
        ),
        migrations.RenameField(
            model_name='submitassignment',
            old_name='user',
            new_name='student',
        ),
    ]
